#!/bin/bash

USER=`whoami`
HOSTNAME=`uname -n`

DISK=`df | grep '^/dev/[hs]d' | awk '{s+=$2} END {print int(s/1048576+0.5)"GB"}'`
ROOT=`df | grep '^/dev/[hs]d' | awk '{s+=$3} END {print int(s/1048576+0.5)"GB"}'`
MEMORY=`free -m | grep "Mem" | awk '{print $2,"-",$3,"-",$4}'`
SWAP=`free -m | grep "Swap" | awk '{print $2,"-",$3,"-",$4}'`
PSA=`ps -Afl | wc -l`

CPU=`ipmitool -I open sensor list | grep -E "CPU Temp"`
FAN1=`ipmitool -I open sensor list | grep -E "FAN1"`
FAN2=`ipmitool -I open sensor list | grep -E "FAN2"`
FAN3=`ipmitool -I open sensor list | grep -E "FAN3"`

CPUREAD=`echo $CPU | awk -F "|" '{print int($2)}' | sed 's/ //g'`
FAN1READ=`echo $FAN1 | awk -F "|" '{print int($2)}' | sed 's/ //g'`
FAN2READ=`echo $FAN2 | awk -F "|" '{print int($2)}' | sed 's/ //g'`
FAN3READ=`echo $FAN3 | awk -F "|" '{print int($2)}' | sed 's/ //g'`

# time of day
HOUR=$(date +"%H")
if [ $HOUR -lt 12  -a $HOUR -ge 0 ]
then    TIME="morning"
elif [ $HOUR -lt 17 -a $HOUR -ge 12 ]
then    TIME="afternoon"
else
TIME="evening"
fi
#System uptime
uptime=`cat /proc/uptime | cut -f1 -d.`
upDays=$((uptime/60/60/24))
upHours=$((uptime/60/60%24))
upMins=$((uptime/60%60))
upSecs=$((uptime%60))
#System load
LOAD1=`cat /proc/loadavg | awk {'print $1'}`
LOAD5=`cat /proc/loadavg | awk {'print $2'}`
LOAD15=`cat /proc/loadavg | awk {'print $3'}`
figlet $(hostname)
printf "\n"
echo -e "\e[7m                         --- Good $TIME $USER ---                         \e[0m"
COLOR_COLUMN="\e[1m-"
COLOR_VALUE="\e[31m"
RESET_COLORS="\e[0m"
echo -e "
===========================================================================
$COLOR_COLUMN- Hostname$RESET_COLORS............: $COLOR_VALUE $HOSTNAME $RESET_COLORS
$COLOR_COLUMN- Release$RESET_COLORS.............: $COLOR_VALUE `cat /etc/redhat-release` $RESET_COLORS
$COLOR_COLUMN- Users$RESET_COLORS...............: $COLOR_VALUE Currently `users | wc -w` user(s) logged on $RESET_COLORS
=========================================================================== $RESET_COLORS
$COLOR_COLUMN- Current user$RESET_COLORS........: $COLOR_VALUE $USER $RESET_COLORS
$COLOR_COLUMN- CPU usage$RESET_COLORS...........: $COLOR_VALUE $LOAD1 - $LOAD5 - $LOAD15 (1-5-15 min) $RESET_COLORS
$COLOR_COLUMN- Memory used$RESET_COLORS.........: $COLOR_VALUE $MEMORY (total-free-used) $RESET_COLORS
$COLOR_COLUMN- Swap in use$RESET_COLORS.........: $COLOR_VALUE $SWAP (total-used-free) MB $RESET_COLORS
$COLOR_COLUMN- Processes$RESET_COLORS...........: $COLOR_VALUE $PSA 个进程正在运行 $RESET_COLORS
$COLOR_COLUMN- System uptime$RESET_COLORS.......: $COLOR_VALUE $upDays 天 $upHours 小时 $upMins 分钟 $upSecs 秒 $RESET_COLORS
$COLOR_COLUMN- Disk space All$RESET_COLORS......: $COLOR_VALUE $DISK $RESET_COLORS
$COLOR_COLUMN- Disk space Used$RESET_COLORS.....: $COLOR_VALUE $ROOT $RESET_COLORS
$COLOR_COLUMN- CPU Temperature$RESET_COLORS.....: $COLOR_VALUE $CPUREAD ℃ $RESET_COLORS
$COLOR_COLUMN- FAN Rotating Speed$RESET_COLORS..: $COLOR_VALUE $FAN1READ"rpm" - $FAN2READ"rpm" - $FAN3READ"rpm" (FAN1~3转速)$RESET_COLORS
===========================================================================
"
